# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
github: AnshulJ999
patreon: AnshulJain
ko_fi: anshul99
custom: https://paypal.me/AnshulJain99
